[package]
name = "pulseshitter"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulsectl-rs = "0.3.2"
serde = "1.0.156"
ron = "0.8.0"
crossbeam = "0.8.2"
songbird = "0.3.1"
serenity = {version = "0.11.5", default-features = false, features = ["builder", "cache", "client", "voice"]}
tokio = {version = "1.26.0", features = ["full"]}
tui = "0.19"
crossterm = "0.25"