[package]
name = "pulseshitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulsectl-rs = "0.3.2"
songbird = "0.3.1"
serenity = "0.11.5"
tokio = {version = "1.26.0", features = ["full"]}